apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: evm-mcp-server-prd

patches:
  - target:
      kind: HTTPRoute
      name: evm-mcp-server
    patch: |-
      - op: replace
        path: "/spec/hostnames/0"
        value: evm.mcp.zilliqa.com
      - op: replace
        path: "/spec/parentRefs/0/name"
        value: gke-gateway
      - op: replace
        path: "/spec/parentRefs/0/namespace"
        value: gke-gateway-prd
